version: '3'

includes:
  app:
    taskfile: ./cmd/Taskfile.yml
  build:
    taskfile: ./build/TaskfileDocker.yml
  common:
    taskfile: ./TaskfileCommon.yml
  infra:
    dir: ./infra
    taskfile: ./infra/Taskfile.yml    
  provision:
    taskfile: ./TaskfileProvision.yml
