networks:
  deblock-external-network:
    driver: bridge

services:
  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    networks:
      - deblock-external-network    
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - "8080:8080"
    links:
      - kafka

  kafka:
    image: 'bitnami/kafka:3.8-debian-12'
    restart: unless-stopped    
    volumes:
      - ./data/kafka:/bitnami/kafka
    networks:
      - deblock-external-network
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 
    ports:
      - "9092:9092"

  create-topics:
    image: 'bitnami/kafka:3.8-debian-12'
    depends_on:
      - kafka
    volumes:
      - ./tools/kafka/create-topics.sh:/create-topics.sh
    networks:
      - deblock-external-network
    entrypoint: ["/bin/bash", "-c", "/create-topics.sh"]