version: '3'

tasks:
  # Bitcoin
  start:bitcoin-block-processor:
    desc: Start the Bitcoin block processor
    cmds:
      - task: build:bitcoin-block-processor
      - ./build/services/bitcoin-block-processor/bitcoin-block-processor --config ./dev/config/bitcoin-block-processor --env ./dev/config
  build:bitcoin-block-processor:
    desc: Build the Bitcoin block processor
    cmds:
      - CGO_ENABLED=1 go build -o ./build/services/bitcoin-block-processor/bitcoin-block-processor ./cmd/bitcoin/blockprocessor/main.go
  delete:database:bitcoin-block-processor:
    desc: Delete the Bitcoin block processor database
    cmds:
      - rm -f ./dev/data/bitcoin-block-processor/bitcoin-block-processor.db

  start:bitcoin-transaction-processor:
    desc: Start the Bitcoin transaction processor
    cmds:
      - task: build:bitcoin-transaction-processor
      - ./build/services/bitcoin-transaction-processor/bitcoin-transaction-processor --config ./dev/config/bitcoin-transaction-processor --env ./dev/config
  build:bitcoin-transaction-processor:
    desc: Build the Bitcoin transaction processor
    cmds:
      - CGO_ENABLED=0 go build -o ./build/services/bitcoin-transaction-processor/bitcoin-transaction-processor ./cmd/bitcoin/transactionprocessor/main.go

  # Ethereum        
  start:ethereum-block-processor:
    desc: Start the Ethereum block processor
    cmds:
      - task: build:ethereum-block-processor
      - ./build/services/ethereum-block-processor/ethereum-block-processor --config ./dev/config/ethereum-block-processor --env ./dev/config
  build:ethereum-block-processor:
    desc: Build the Ethereum block processor
    cmds:
      - CGO_ENABLED=1 go build -o ./build/services/ethereum-block-processor/ethereum-block-processor ./cmd/ethereum/blockprocessor/main.go
  delete:database:ethereum-block-processor:
    desc: Delete the Ethereum block processor database
    cmds:
      - rm -f ./dev/data/ethereum-block-processor/ethereum-block-processor.db

  start:ethereum-transaction-processor:
    desc: Start the Ethereum transaction processor
    cmds:
      - task: build:ethereum-transaction-processor
      - ./build/services/ethereum-transaction-processor/ethereum-transaction-processor --config ./dev/config/ethereum-transaction-processor --env ./dev/config
  build:ethereum-transaction-processor:
    desc: Build the Ethereum transaction processor
    cmds:
      - CGO_ENABLED=0 go build -o ./build/services/ethereum-transaction-processor/ethereum-transaction-processor ./cmd/ethereum/transactionprocessor/main.go

  # Solana        
  start:solana-block-processor:
    desc: Start the Solana block processor
    cmds:
      - task: build:solana-block-processor
      - ./build/services/solana-block-processor/solana-block-processor --config ./dev/config/solana-block-processor --env ./dev/config
  build:solana-block-processor:
    desc: Build the Solana block processor
    cmds:
      - CGO_ENABLED=1 go build -o ./build/services/solana-block-processor/solana-block-processor ./cmd/solana/blockprocessor/main.go
  delete:database:solana-block-processor:
    desc: Delete the Solana block processor database
    cmds:
      - rm -f ./dev/data/solana-block-processor/solana-block-processor.db

  start:solana-transaction-processor:
    desc: Start the Solana transaction processor
    cmds:
      - task: build:solana-transaction-processor
      - ./build/services/solana-transaction-processor/solana-transaction-processor --config ./dev/config/solana-transaction-processor --env ./dev/config
  build:solana-transaction-processor:
    desc: Build the Solana transaction processor
    cmds:
      - CGO_ENABLED=0 go build -o ./build/services/solana-transaction-processor/solana-transaction-processor ./cmd/solana/transactionprocessor/main.go
  
  # Common
  start:all:
    desc: Start all processors
    deps:
      - task: start:bitcoin-block-processor
      - task: start:bitcoin-transaction-processor
      - task: start:ethereum-block-processor
      - task: start:ethereum-transaction-processor   
      - task: start:solana-block-processor
      - task: start:solana-transaction-processor
    
  delete:database:all:
    desc: Delete all databases
    cmds:
      - task: delete:database:bitcoin-block-processor
      - task: delete:database:ethereum-block-processor
      - task: delete:database:solana-block-processor             